---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.x
    - tip
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - make all
    - make cover
    - make release
  after_success:
    - bash <(curl -s https://codecov.io/bash)
  deploy:
    provider: releases
    api_key:
      secure: "ZQ9AnuXWZcsmazWHp9EsSJgOA/+8KZdCmL5lKh2PbD4y7MqSglBDExkhU37MP/cF8UAccjlIlIaM4gBCRuER/Q8Dn4WBU08pjJkdGvexy2yEOTKYnoxski80OjH7nL41EVFKDDpaOjFU3B8ply4uJBgrAk2iYwyZw2dkOefy44jq5QTrZxOLJLckt+xJY7yaNP60K/UL1tXbbPML+gmZ6Yhy/8bwhqFWuX3WwDTEOvq1I0Q2g7JXMsSVMExKhuDPGxCyMAvy4z9cFWBh9A0ixEpWmdeY+3X7MhVLk8JQ58g4ST7L7jlYs6ds+pmtckOS195yotqi8Ex+WQkU/ohKs4Kh+xBBan1rCW7ZVA9SFvcaKnjQ4LEKhtW5WilGMQT9cBIdCRtyJIQI7U3xxcDrF2fkBlQrxz+chPHqd0r34avGe1aHht5dWxYJsoP16fkBgeJ39ndpPTeszn6oHrBg0t0ZNJUye9Kl9u1YemhRh7FSMGnXFjhDGEn7OQY51Z6zsIQpptBJjVLWMxyAAaEY5xROXVtePtOP3ghQrjuBfa8Ym5yLZZFd32DW7qUG7kLiWcBkPitDzXWkTzUlj8kzoSpY9P79QDDniLWnr/W2UJJXVhSUpTEqBYnn67M7JKOedK8cw5FCBtIChi6t4ecN8rnTkdkUcyMht2ftPzcerxI="
    file:
      - cross/releases-linux-amd64.md5
      - cross/releases-windows-386.sha256
      - cross/releases-linux-arm
      - cross/releases-darwin-amd64.md5
      - cross/releases-darwin-amd64
      - cross/releases-solaris-amd64.md5
      - cross/releases-linux-arm64.sha256
      - cross/releases-linux-arm.sha256
      - cross/releases-linux-386.sha256
      - cross/releases-darwin-386.md5
      - cross/releases-windows-386.md5
      - cross/releases-freebsd-amd64.md5
      - cross/releases-linux-arm64.md5
      - cross/releases-linux-arm64
      - cross/releases-freebsd-amd64.sha256
      - cross/releases-freebsd-386.md5
      - cross/releases-linux-amd64.sha256
      - cross/releases-linux-386.md5
      - cross/releases-freebsd-386
      - cross/releases-solaris-amd64.sha256
      - cross/releases-windows-amd64
      - cross/releases-windows-amd64.md5
      - cross/releases-windows-amd64.sha256
      - cross/releases-linux-arm.md5
      - cross/releases-darwin-386.sha256
      - cross/releases-darwin-amd64.sha256
      - cross/releases-windows-386
      - cross/releases-solaris-amd64
      - cross/releases-darwin-386
      - cross/releases-linux-386
      - cross/releases-freebsd-amd64
      - cross/releases-freebsd-386.sha256
      - cross/releases-linux-amd64
    skip_cleanup: true
    on:
      tags: true
